source 'https://rubygems.org'
ruby '2.4.1'

gem 'sinatra'
gem 'data_mapper', '1.2.0'
gem 'dm-postgres-adapter'
gem 'dm-migrations'

group :test do
  gem 'json'
  gem 'rspec'
  gem 'rspec-sinatra'
  gem 'capybara'
  gem 'database_cleaner'
end
